### ISSUE TITLE
Update values in `devcontainer.json` are not respected after the container is created

### ISSUE THREAD

**Issue by edgonmsft** [devcontainers/cli#252]
Version 0.74.0

Updated values, such as `remoteEnv` in `devcontainer.json` after the container is created are not respected since the values from the container metadata are taking precedence.

This breaks flows where this values are updated, like secrets, to keep environments working.

The issue appears to be coming from here: https://github.com/devcontainers/cli/blob/dadf77bf0d0f7047fc935f4b56ceeda463860295/src/spec-node/imageMetadata.ts#L119-L149

**Comment by chrmarti** [comment]
The difficulty here is that `imageMetadata` has the properties from the initial devcontainer.json as its last entry if our CLI created the container as a dev container (e.g., a non-dev container in Compose could still have metadata entries, other tools might do something different).

To make sure we don't replace the wrong metadata entry, I suggest we update only the properties that are straight-forward to merge: `remoteEnv`, `remoteUser` and `userEnvProbe`.

Alternatively we could surface the option `--remote-env` to allow for adding / overwriting environment variables.

**Comment by chrmarti** [comment]
Fixed in 0.262.1-pre-release. To verify in the Dev Containers extension:
- Create a dev container with a variable in `"remoteEnv"`.
- Change the variable's value and add another variable.
- Reload the window.
- Verify the environment variables are updated in a new terminal (restored terminals won't update their environment).
