### ISSUE TITLE
How to use docker compose V2 via devcontainer cli

### ISSUE THREAD

**Issue by yokonao** [devcontainers/cli#485]
Hi! Thank you for always developing nice tools.

I want to know the best practice for using docker compose V2.
My workaround is here.

```docker-compose.sh
#!/bin/sh

docker compose "$@"
```

Pass the above shell script to `--docker-compose-path` option.
```.sh
$ devcontainer build --workspace-folder . --docker-compose-path /path/to/docker-compose.sh
```

I suspect that there is more better solution.

**Comment by yokonao** [comment]
Thanks for info! I did not know that. In my environment, dokcer-compose is isntalled too because some tools depend V1.

My promblem may be solved, thank you!

However, docker compose V1 is about to EOL. I hope that V2 takes precedence over V1 in devcontainer cli.

**Comment by chrmarti** [comment]
> However, docker compose V1 is about to EOL. I hope that V2 takes precedence over V1 in devcontainer cli.

We might do that in the future, for now we will keep it as-is to avoid breaking existing setups. Thanks.

**Comment by AngellusMortis** [comment]
docker compose v1 is fulled EOL'd as of July. https://docs.docker.com/compose/install/

> Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases. Compose V2 has replaced it and is now integrated into all current Docker Desktop versions. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).

Can we get devcontainers to reverse the behavior yet? I do not think it should be defaulting to an EOL piece of software that does not receive security updates anymore. That would be like using Python 2 instead of Python 3 just because they are both installed on the system. 

You could add a deprecation warning that can be suppressed with a setting in VS Code / CLI option to suppress it and then a month or two after that switch to using docker compose v2.
