### ISSUE TITLE
`devcontainer open` command removed

### ISSUE THREAD

**Issue by nataziel** [devcontainers/cli#789]
I couldn't work out how to update the CLI version via VSCode, so I re-installed via `npm`. The new version (0.58.0) does not appear to have a `devcontainer open` command.

I'm a little confused about the differences between the two different distributions, but happily the 0.58.0 release resolves the errors/warnings that were being thrown by the CLI as per: https://github.com/devcontainers/cli/issues/783

Is there a way to update the version included by VSCode, or a way to restore the `devcontainer open` functionality?

**Comment by chrmarti** [comment]
The fix for #783 is in the latest Dev Containers pre-release version 0.353.0 and will be part of the stable release later this week (released alongside VS Code 1.88).

Only the extension's version of the CLI comes with the `open` command since that depends on VS Code while the @devcontainer/cli is independent of VS Code.

**Comment by nataziel** [comment]
Ok that makes sense. Might be a good idea to document the difference in functionality somewhere as the difference is subtle and not explained anywhere (that I could find).

Will close this issue.
