### ISSUE TITLE
Feature Request: Allow devcontainer up to Start Only the Specified Service and Its Dependencies

### ISSUE THREAD

**Issue by vitebo** [devcontainers/cli#835]
Today, I have a fully dockerized development environment in the company where I work, structured as follows:

```
boot/
|- docker-compose.yaml
|- envs/
|- project-1/
|- project-2/
|- project-3/
|- project-4/
```

This setup works well (with some issues), but the concept of dev containers seems to offer a significant improvement in the developer experience (DX).

I want to use dev containers with a similar structure, and it appears to be functional. Here is an example of `project-1/.devcontainer/devcontainer.json`:

```json
{
  "name": "project-1",
  "service": "project-1",
  "dockerComposeFile": ["../../docker-compose.yaml"],
  "workspaceFolder": "/workspace",
  "postCreateCommand": "npm install",
  "shutdownAction": "stopCompose",
  "customizations": {
    "vscode": {
      "extensions": [
        "nrwl.angular-console"
      ]
    }
  }
}
```

The main issue is that I can't start just one service at a time. When I run the command `devcontainer --workspace-folder ./project-1 up`, all services defined in the Docker Compose file are started.

It would be amazing if the CLI could start only the specified service along with its dependencies as defined by the `depends_on` flag in docker-compose.

**Comment by samruddhikhandale** [comment]
The behavior you're seeing is expected because when you use Docker Compose, it starts all services defined in the Docker Compose file by default. However, you can override this behavior by specifying the service(s) you want to start on the command line.

Unfortunately, the devcontainer CLI does not currently support this feature. It always starts all services defined in the Docker Compose file. This is a limitation of the devcontainer CLI and not Docker Compose.

One workaround could be to split your Docker Compose file into multiple files, one for each service and its dependencies. Then, in your devcontainer.json file, you can specify the Docker Compose file for the specific service you want to start.

// cc @chrmarti

**Comment by chrmarti** [comment]
@vitebo Could you give `"runServices"` in the devcontainer.json a try? You set it to an array of strings listing the services you want to start/stop with that dev container.

**Comment by vitebo** [comment]
cool, this `runServices` worked great for my case, thank you very much.

A cool curiosity is that I don't need to list the entire dependency tree in the `runServices` option, I can only list the direct dependents and in these cases the docker-compose key `depends_on` is respected, for example:

```yaml
# docker-compose.yaml

project-1:
  build: ./project-1/.devcontainer
  depends_on:
    - postgres
    - redis

project-2:
  build: ./project-2/.devcontainer
```

```json5
// project-2/.devcontainer/devcontainer.json
{
  "name": "project-2",
  "runServices": ["project-1"],
  "dockerComposeFile": ["../../docker-compose.yaml"],
  "workspaceFolder": "/workspace",
}
```

I don't need to say in `devcontainer.json` that `project-1` depends on postgres and redis.

Thanks a lot for the help

**Comment by chrmarti** [comment]
Great, thanks @vitebo !
