### ISSUE TITLE
Issues executing binary inside container with devcontainer exec

### ISSUE THREAD

**Issue by bamurtaugh** [devcontainers/cli#862]
From https://x.com/melodyogonna/status/1816137549552746580:

> I'm having issues executing any binary that's inside the container with devcontainer exec, attached is the dockerfile I have, and an example of the error I get.
> 
> This devcontainer builds successfully and also starts successfully.

![Image](https://github.com/user-attachments/assets/834c7a6a-461b-47e2-a737-0287d286f768)

![Image](https://github.com/user-attachments/assets/a0ebafef-85d5-4049-bcc6-98c3401c1034)

@chrmarti @samruddhikhandale would love to get your thoughts on this one!

**Comment by chrmarti** [comment]
This seems to work for me. Which version are you using? (`devcontainer --version`)

**Comment by melodyogonna** [comment]
Hey @chrmarti, the devcontainer version is 0.65.0, on Mac OS 12.7.5 x86. However, I have realized the issue has less to do with devcontainer and more to do with docker itself as `docker exec nvim` doesn't work, and searching all of the path directories (after `docker exec -it /bin/sh`) doesn't turn up the binaries anywhere. I'm still investigating the issue.

**Comment by melodyogonna** [comment]
I am narrowing the problem further.
If I run docker interactively on the image created by devcontainer (`docker run -it vsc-mojo-7d54138114c9814c2d5f1a56ce4cd468f218c567f94945052730c57565f49ead`), every installed binary is available. The problem then seems to be with the container created by `devcontainer up`

**Comment by melodyogonna** [comment]
Update:
I looked at the output of `docker ps` again and just realized the container being started was created 4 weeks ago, when I ran `devcontainer up` the first time (and before I even started using a docker file). The changes I've made to devcontainer.json since then were apparently not enough to recreate the container, am I wrong to assume it would?

Anyway, after manually removing the container, a new one has been created using my Dockerfile, and every binary now works. 

@bamurtaugh you can close this issue now, thank you for following up with me.

**Comment by bamurtaugh** [comment]
Thank you for all the follow up and troubleshooting!
